parameters:
    router.options:
        cache_dir: '%kernel.cache_dir%'
        debug: '%kernel.debug%'
        resource_type: '%router.resource_type%'
        generator_class: 'Symfony\Component\Routing\Generator\CompiledUrlGenerator'
        generator_dumper_class: 'Symfony\Component\Routing\Generator\Dumper\CompiledUrlGeneratorDumper'
        matcher_class: 'Symfony\Component\Routing\Matcher\CompiledUrlMatcher'
        matcher_dumper_class: 'Symfony\Component\Routing\Matcher\Dumper\CompiledUrlMatcherDumper'

services:
    router:
        class: 'Symfony\Component\Routing\Router'
        public: false
        arguments:
            - '@routing.loader'
            - '%router.resource%'
            - '%router.options%'
            - '@router.request_context'
        calls:
            - [ setConfigCacheFactory, ['@config_cache_factory'] ]

    'Symfony\Component\Routing\RouterInterface':
        alias: router

    routing.loader:
        class: 'Symfony\Component\Config\Loader\DelegatingLoader'
        public: false
        arguments:
            - '@routing.resolver'

    routing.resolver:
        class: 'Symfony\Component\Config\Loader\LoaderResolver'
        public: false

    router.request_context:
        class: 'Symfony\Component\Routing\RequestContext'
        public: false

    'Symfony\Component\Routing\RequestContext':
        alias: router.request_context

    config_cache_factory:
        class: 'Symfony\Component\Config\ResourceCheckerConfigCacheFactory'
        public: false
