parameters:
    router.options:
        cache_dir: '%kernel.cache_dir%'
        debug: '%kernel.debug%'
        resource_type: '%router.resource_type%'
        generator_cache_class: '%router.cache_class_prefix%UrlGenerator'
        matcher_cache_class: '%router.cache_class_prefix%UrlMatcher'

services:
    router:
        class: 'Symfony\Component\Routing\Router'
        public: false
        arguments:
            - '@routing.loader'
            - '%router.resource%'
            - '%router.options%'
            - '@router.request_context'
        calls:
            - [ setConfigCacheFactory, ['@config_cache_factory'] ]

    'Symfony\Component\Routing\RouterInterface':
        alias: router

    routing.loader:
        class: 'Symfony\Component\Config\Loader\DelegatingLoader'
        public: false
        arguments:
            - '@routing.resolver'

    routing.resolver:
        class: 'Symfony\Component\Config\Loader\LoaderResolver'
        public: false

    router.request_context:
        class: 'Symfony\Component\Routing\RequestContext'
        public: false

    'Symfony\Component\Routing\RequestContext':
        alias: router.request_context

    config_cache_factory:
        class: 'Symfony\Component\Config\ResourceCheckerConfigCacheFactory'
        public: false
