<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerY8n5QOM\AppTestProjectContainer::class, false)) {
    require __DIR__.'/ContainerY8n5QOM/AppTestProjectContainer.php';
}

if (!class_exists(AppTestProjectContainer::class, false)) {
    class_alias(\ContainerY8n5QOM\AppTestProjectContainer::class, AppTestProjectContainer::class, false);
}

return new \ContainerY8n5QOM\AppTestProjectContainer();
