<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_clear_command' shared service.

$this->services['cache_clear_command'] = $instance = new \Gnugat\MicroFrameworkBundle\Command\CacheClearCommand(new \Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer(array(0 => new \Gnugat\MicroFrameworkBundle\Service\KernelCacheClearer())), $this->targetDirs[0]);

$instance->setName('cache:clear');

return $instance;
