<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_warmup_command' shared service.

$a = new \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate(array());
$a->enableOptionalWarmers();

$this->services['cache_warmup_command'] = $instance = new \Gnugat\MicroFrameworkBundle\Command\CacheWarmupCommand($a, $this->targetDirs[0]);

$instance->setName('cache:warmup');

return $instance;
