<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'event_dispatcher' shared service.

$this->services['event_dispatcher'] = $instance = new \Symfony\Component\EventDispatcher\EventDispatcher($this);

$instance->addListener('kernel.response', array(0 => function () {
    return ($this->privates['response_listener'] ?? $this->privates['response_listener'] = new \Symfony\Component\HttpKernel\EventListener\ResponseListener('UTF-8'));
}, 1 => 'onKernelResponse'), 0);
$instance->addListener('kernel.request', array(0 => function () {
    return ($this->privates['router_listener'] ?? $this->load(__DIR__.'/getRouterListenerService.php'));
}, 1 => 'onKernelRequest'), 32);
$instance->addListener('kernel.finish_request', array(0 => function () {
    return ($this->privates['router_listener'] ?? $this->load(__DIR__.'/getRouterListenerService.php'));
}, 1 => 'onKernelFinishRequest'), 0);

return $instance;
