<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'http_kernel' shared service.

return $this->services['http_kernel'] = new \Symfony\Component\HttpKernel\HttpKernel(($this->services['event_dispatcher'] ?? $this->load(__DIR__.'/getEventDispatcherService.php')), new \Gnugat\MicroFrameworkBundle\Service\ServiceControllerResolver($this, new \Symfony\Component\HttpKernel\Controller\ControllerResolver()), ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
