<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Service\MyService' shared service.

return $this->services['tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Service\MyService'] = new \tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Service\MyService();
