<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Command\SayHelloAwareCommand' shared service.

$this->services['tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Command\SayHelloAwareCommand'] = $instance = new \tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Command\SayHelloAwareCommand();

$instance->setName('say-hello-aware');

return $instance;
