<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\CommandBus\SayHelloHandler' shared service.

return $this->services['tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\CommandBus\SayHelloHandler'] = new \tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\CommandBus\SayHelloHandler(($this->services['logger'] ?? $this->load(__DIR__.'/getLoggerService.php')));
