<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Command\SayHelloCommand' shared service.

$this->services['tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Command\SayHelloCommand'] = $instance = new \tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\Command\SayHelloCommand(($this->services['tests\Gnugat\MicroFrameworkBundle\CustomBundle\src\CommandBus\SayHelloHandler'] ?? $this->load(__DIR__.'/getSayHelloHandlerService.php')));

$instance->setName('say-helo');

return $instance;
